//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OriginX.Language {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppLang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OriginX.Language.AppLang", typeof(AppLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关 的本地化字符串。
        /// </summary>
        public static string Close1 {
            get {
                return ResourceManager.GetString("Close1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minecraft 版本信息 的本地化字符串。
        /// </summary>
        public static string MinecraftVersionInfo {
            get {
                return ResourceManager.GetString("MinecraftVersionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开 的本地化字符串。
        /// </summary>
        public static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关 的本地化字符串。
        /// </summary>
        public static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 State 不能为空 的本地化字符串。
        /// </summary>
        public static string State不能为空 {
            get {
                return ResourceManager.GetString("State不能为空", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载 的本地化字符串。
        /// </summary>
        public static string 下载 {
            get {
                return ResourceManager.GetString("下载", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主页 的本地化字符串。
        /// </summary>
        public static string 主页 {
            get {
                return ResourceManager.GetString("主页", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 代码 的本地化字符串。
        /// </summary>
        public static string 代码 {
            get {
                return ResourceManager.GetString("代码", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}不能为空，请指定有效的值 的本地化字符串。
        /// </summary>
        public static string 值不能为空 {
            get {
                return ResourceManager.GetString("值不能为空", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公开 的本地化字符串。
        /// </summary>
        public static string 公开 {
            get {
                return ResourceManager.GetString("公开", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 准备就绪 的本地化字符串。
        /// </summary>
        public static string 准备就绪 {
            get {
                return ResourceManager.GetString("准备就绪", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 切换账户 的本地化字符串。
        /// </summary>
        public static string 切换账户 {
            get {
                return ResourceManager.GetString("切换账户", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷新 的本地化字符串。
        /// </summary>
        public static string 刷新 {
            get {
                return ResourceManager.GetString("刷新", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷新Token不能为空 的本地化字符串。
        /// </summary>
        public static string 刷新Token不能为空 {
            get {
                return ResourceManager.GetString("刷新Token不能为空", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载器版本 的本地化字符串。
        /// </summary>
        public static string 加载器版本 {
            get {
                return ResourceManager.GetString("加载器版本", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发布时间： 的本地化字符串。
        /// </summary>
        public static string 发布时间 {
            get {
                return ResourceManager.GetString("发布时间", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string 取消 {
            get {
                return ResourceManager.GetString("取消", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称格式错误 的本地化字符串。
        /// </summary>
        public static string 名称格式错误 {
            get {
                return ResourceManager.GetString("名称格式错误", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 后台下载 的本地化字符串。
        /// </summary>
        public static string 后台下载 {
            get {
                return ResourceManager.GetString("后台下载", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存在 的本地化字符串。
        /// </summary>
        public static string 存在 {
            get {
                return ResourceManager.GetString("存在", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 安装 的本地化字符串。
        /// </summary>
        public static string 安装 {
            get {
                return ResourceManager.GetString("安装", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帮助 的本地化字符串。
        /// </summary>
        public static string 帮助 {
            get {
                return ResourceManager.GetString("帮助", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Origin X 的本地化字符串。
        /// </summary>
        public static string 应用标题 {
            get {
                return ResourceManager.GetString("应用标题", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始 的本地化字符串。
        /// </summary>
        public static string 开始 {
            get {
                return ResourceManager.GetString("开始", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始游戏 的本地化字符串。
        /// </summary>
        public static string 开始游戏 {
            get {
                return ResourceManager.GetString("开始游戏", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开放源代码 的本地化字符串。
        /// </summary>
        public static string 开放源代码 {
            get {
                return ResourceManager.GetString("开放源代码", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前选择： 的本地化字符串。
        /// </summary>
        public static string 当前选择 {
            get {
                return ResourceManager.GetString("当前选择", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 微软 的本地化字符串。
        /// </summary>
        public static string 微软 {
            get {
                return ResourceManager.GetString("微软", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 微软登录 的本地化字符串。
        /// </summary>
        public static string 微软登录 {
            get {
                return ResourceManager.GetString("微软登录", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 快照版 的本地化字符串。
        /// </summary>
        public static string 快照版 {
            get {
                return ResourceManager.GetString("快照版", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您确定要退出吗？ 的本地化字符串。
        /// </summary>
        public static string 您确定要退出吗 {
            get {
                return ResourceManager.GetString("您确定要退出吗", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开 的本地化字符串。
        /// </summary>
        public static string 打开 {
            get {
                return ResourceManager.GetString("打开", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 授权代码不能为空 的本地化字符串。
        /// </summary>
        public static string 授权代码不能为空 {
            get {
                return ResourceManager.GetString("授权代码不能为空", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        public static string 提示 {
            get {
                return ResourceManager.GetString("提示", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索版本 的本地化字符串。
        /// </summary>
        public static string 搜索版本 {
            get {
                return ResourceManager.GetString("搜索版本", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 旧Alpha版 的本地化字符串。
        /// </summary>
        public static string 旧Alpha版 {
            get {
                return ResourceManager.GetString("旧Alpha版", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 旧测试版 的本地化字符串。
        /// </summary>
        public static string 旧测试版 {
            get {
                return ResourceManager.GetString("旧测试版", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最大长度：{0} 的本地化字符串。
        /// </summary>
        public static string 最大长度 {
            get {
                return ResourceManager.GetString("最大长度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最小长度：{0} 的本地化字符串。
        /// </summary>
        public static string 最小长度 {
            get {
                return ResourceManager.GetString("最小长度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最新 的本地化字符串。
        /// </summary>
        public static string 最新 {
            get {
                return ResourceManager.GetString("最新", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最新版本 的本地化字符串。
        /// </summary>
        public static string 最新版本 {
            get {
                return ResourceManager.GetString("最新版本", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正式版 的本地化字符串。
        /// </summary>
        public static string 正式版 {
            get {
                return ResourceManager.GetString("正式版", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 步骤 的本地化字符串。
        /// </summary>
        public static string 步骤 {
            get {
                return ResourceManager.GetString("步骤", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有下载信息 的本地化字符串。
        /// </summary>
        public static string 没有下载信息 {
            get {
                return ResourceManager.GetString("没有下载信息", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏 的本地化字符串。
        /// </summary>
        public static string 游戏 {
            get {
                return ResourceManager.GetString("游戏", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏名称 的本地化字符串。
        /// </summary>
        public static string 游戏名称 {
            get {
                return ResourceManager.GetString("游戏名称", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏版本 的本地化字符串。
        /// </summary>
        public static string 游戏版本 {
            get {
                return ResourceManager.GetString("游戏版本", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏版本名称 的本地化字符串。
        /// </summary>
        public static string 游戏版本名称 {
            get {
                return ResourceManager.GetString("游戏版本名称", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 源 的本地化字符串。
        /// </summary>
        public static string 源 {
            get {
                return ResourceManager.GetString("源", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版本名称 的本地化字符串。
        /// </summary>
        public static string 版本名称 {
            get {
                return ResourceManager.GetString("版本名称", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版本管理 的本地化字符串。
        /// </summary>
        public static string 版本管理 {
            get {
                return ResourceManager.GetString("版本管理", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 玩 的本地化字符串。
        /// </summary>
        public static string 玩 {
            get {
                return ResourceManager.GetString("玩", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户 的本地化字符串。
        /// </summary>
        public static string 用户 {
            get {
                return ResourceManager.GetString("用户", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录 的本地化字符串。
        /// </summary>
        public static string 登录 {
            get {
                return ResourceManager.GetString("登录", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录 Minecraft 的本地化字符串。
        /// </summary>
        public static string 登录Minecraft {
            get {
                return ResourceManager.GetString("登录Minecraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 离线 的本地化字符串。
        /// </summary>
        public static string 离线 {
            get {
                return ResourceManager.GetString("离线", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 离线登录 的本地化字符串。
        /// </summary>
        public static string 离线登录 {
            get {
                return ResourceManager.GetString("离线登录", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 空 的本地化字符串。
        /// </summary>
        public static string 空 {
            get {
                return ResourceManager.GetString("空", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 视图模型实例与指定类型不匹配 的本地化字符串。
        /// </summary>
        public static string 视图模型实例与指定类型不匹配 {
            get {
                return ResourceManager.GetString("视图模型实例与指定类型不匹配", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色名称 的本地化字符串。
        /// </summary>
        public static string 角色名称 {
            get {
                return ResourceManager.GetString("角色名称", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 许可证 的本地化字符串。
        /// </summary>
        public static string 许可证 {
            get {
                return ResourceManager.GetString("许可证", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        public static string 设置 {
            get {
                return ResourceManager.GetString("设置", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 说明 的本地化字符串。
        /// </summary>
        public static string 说明 {
            get {
                return ResourceManager.GetString("说明", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 账户 的本地化字符串。
        /// </summary>
        public static string 账户 {
            get {
                return ResourceManager.GetString("账户", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 账户管理 的本地化字符串。
        /// </summary>
        public static string 账户管理 {
            get {
                return ResourceManager.GetString("账户管理", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 跳过加载器 的本地化字符串。
        /// </summary>
        public static string 跳过加载器 {
            get {
                return ResourceManager.GetString("跳过加载器", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入 的本地化字符串。
        /// </summary>
        public static string 输入 {
            get {
                return ResourceManager.GetString("输入", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入密码 的本地化字符串。
        /// </summary>
        public static string 输入密码 {
            get {
                return ResourceManager.GetString("输入密码", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入电子邮件 的本地化字符串。
        /// </summary>
        public static string 输入电子邮件 {
            get {
                return ResourceManager.GetString("输入电子邮件", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入角色名称 的本地化字符串。
        /// </summary>
        public static string 输入角色名称 {
            get {
                return ResourceManager.GetString("输入角色名称", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入邮箱 的本地化字符串。
        /// </summary>
        public static string 输入邮箱 {
            get {
                return ResourceManager.GetString("输入邮箱", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 返回 的本地化字符串。
        /// </summary>
        public static string 返回 {
            get {
                return ResourceManager.GetString("返回", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出 的本地化字符串。
        /// </summary>
        public static string 退出 {
            get {
                return ResourceManager.GetString("退出", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出登录 的本地化字符串。
        /// </summary>
        public static string 退出登录 {
            get {
                return ResourceManager.GetString("退出登录", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择 Minecraft 的本地化字符串。
        /// </summary>
        public static string 选择_Minecraft {
            get {
                return ResourceManager.GetString("选择 Minecraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择 Mod 加载器 的本地化字符串。
        /// </summary>
        public static string 选择_Mod_加载器 {
            get {
                return ResourceManager.GetString("选择 Mod 加载器", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 预览 的本地化字符串。
        /// </summary>
        public static string 预览 {
            get {
                return ResourceManager.GetString("预览", resourceCulture);
            }
        }
    }
}
