//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OriginX.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppLang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OriginX.Language.AppLang", typeof(AppLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关闭.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关.
        /// </summary>
        public static string Close1 {
            get {
                return ResourceManager.GetString("Close1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minecraft 版本信息.
        /// </summary>
        public static string MinecraftVersionInfo {
            get {
                return ResourceManager.GetString("MinecraftVersionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开.
        /// </summary>
        public static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关.
        /// </summary>
        public static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State 不能为空.
        /// </summary>
        public static string State不能为空 {
            get {
                return ResourceManager.GetString("State不能为空", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下载.
        /// </summary>
        public static string 下载 {
            get {
                return ResourceManager.GetString("下载", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下载版本.
        /// </summary>
        public static string 下载版本 {
            get {
                return ResourceManager.GetString("下载版本", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主页.
        /// </summary>
        public static string 主页 {
            get {
                return ResourceManager.GetString("主页", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 代码.
        /// </summary>
        public static string 代码 {
            get {
                return ResourceManager.GetString("代码", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}不能为空，请指定有效的值.
        /// </summary>
        public static string 值不能为空 {
            get {
                return ResourceManager.GetString("值不能为空", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 公开.
        /// </summary>
        public static string 公开 {
            get {
                return ResourceManager.GetString("公开", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最大长度：{0}.
        /// </summary>
        public static string 最大长度 {
            get {
                return ResourceManager.GetString("最大长度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最小长度：{0}.
        /// </summary>
        public static string 最小长度 {
            get {
                return ResourceManager.GetString("最小长度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最新.
        /// </summary>
        public static string 最新 {
            get {
                return ResourceManager.GetString("最新", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最新版本.
        /// </summary>
        public static string 最新版本 {
            get {
                return ResourceManager.GetString("最新版本", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 准备就绪.
        /// </summary>
        public static string 准备就绪 {
            get {
                return ResourceManager.GetString("准备就绪", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 切换账户.
        /// </summary>
        public static string 切换账户 {
            get {
                return ResourceManager.GetString("切换账户", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 刷新.
        /// </summary>
        public static string 刷新 {
            get {
                return ResourceManager.GetString("刷新", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 刷新Token不能为空.
        /// </summary>
        public static string 刷新Token不能为空 {
            get {
                return ResourceManager.GetString("刷新Token不能为空", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 加载器版本.
        /// </summary>
        public static string 加载器版本 {
            get {
                return ResourceManager.GetString("加载器版本", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发布时间：.
        /// </summary>
        public static string 发布时间 {
            get {
                return ResourceManager.GetString("发布时间", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消.
        /// </summary>
        public static string 取消 {
            get {
                return ResourceManager.GetString("取消", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 名称格式错误.
        /// </summary>
        public static string 名称格式错误 {
            get {
                return ResourceManager.GetString("名称格式错误", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 后台下载.
        /// </summary>
        public static string 后台下载 {
            get {
                return ResourceManager.GetString("后台下载", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 存在.
        /// </summary>
        public static string 存在 {
            get {
                return ResourceManager.GetString("存在", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 安装.
        /// </summary>
        public static string 安装 {
            get {
                return ResourceManager.GetString("安装", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 帮助.
        /// </summary>
        public static string 帮助 {
            get {
                return ResourceManager.GetString("帮助", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origin X.
        /// </summary>
        public static string 应用标题 {
            get {
                return ResourceManager.GetString("应用标题", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始.
        /// </summary>
        public static string 开始 {
            get {
                return ResourceManager.GetString("开始", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始游戏.
        /// </summary>
        public static string 开始游戏 {
            get {
                return ResourceManager.GetString("开始游戏", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开放源代码.
        /// </summary>
        public static string 开放源代码 {
            get {
                return ResourceManager.GetString("开放源代码", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前选择：.
        /// </summary>
        public static string 当前选择 {
            get {
                return ResourceManager.GetString("当前选择", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 微软.
        /// </summary>
        public static string 微软 {
            get {
                return ResourceManager.GetString("微软", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 微软登录.
        /// </summary>
        public static string 微软登录 {
            get {
                return ResourceManager.GetString("微软登录", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 快照版.
        /// </summary>
        public static string 快照版 {
            get {
                return ResourceManager.GetString("快照版", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 快照版本.
        /// </summary>
        public static string 快照版本 {
            get {
                return ResourceManager.GetString("快照版本", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您确定要退出吗？.
        /// </summary>
        public static string 您确定要退出吗 {
            get {
                return ResourceManager.GetString("您确定要退出吗", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开.
        /// </summary>
        public static string 打开 {
            get {
                return ResourceManager.GetString("打开", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 授权代码不能为空.
        /// </summary>
        public static string 授权代码不能为空 {
            get {
                return ResourceManager.GetString("授权代码不能为空", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提示.
        /// </summary>
        public static string 提示 {
            get {
                return ResourceManager.GetString("提示", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 搜索版本.
        /// </summary>
        public static string 搜索版本 {
            get {
                return ResourceManager.GetString("搜索版本", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 旧Alpha版.
        /// </summary>
        public static string 旧Alpha版 {
            get {
                return ResourceManager.GetString("旧Alpha版", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 旧测试版.
        /// </summary>
        public static string 旧测试版 {
            get {
                return ResourceManager.GetString("旧测试版", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正式版.
        /// </summary>
        public static string 正式版 {
            get {
                return ResourceManager.GetString("正式版", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正式版本.
        /// </summary>
        public static string 正式版本 {
            get {
                return ResourceManager.GetString("正式版本", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 步骤.
        /// </summary>
        public static string 步骤 {
            get {
                return ResourceManager.GetString("步骤", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 没有下载信息.
        /// </summary>
        public static string 没有下载信息 {
            get {
                return ResourceManager.GetString("没有下载信息", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 游戏.
        /// </summary>
        public static string 游戏 {
            get {
                return ResourceManager.GetString("游戏", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 游戏名称.
        /// </summary>
        public static string 游戏名称 {
            get {
                return ResourceManager.GetString("游戏名称", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 游戏版本.
        /// </summary>
        public static string 游戏版本 {
            get {
                return ResourceManager.GetString("游戏版本", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 游戏版本名称.
        /// </summary>
        public static string 游戏版本名称 {
            get {
                return ResourceManager.GetString("游戏版本名称", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 源.
        /// </summary>
        public static string 源 {
            get {
                return ResourceManager.GetString("源", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 版本名称.
        /// </summary>
        public static string 版本名称 {
            get {
                return ResourceManager.GetString("版本名称", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 版本管理.
        /// </summary>
        public static string 版本管理 {
            get {
                return ResourceManager.GetString("版本管理", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 玩.
        /// </summary>
        public static string 玩 {
            get {
                return ResourceManager.GetString("玩", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户.
        /// </summary>
        public static string 用户 {
            get {
                return ResourceManager.GetString("用户", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登录.
        /// </summary>
        public static string 登录 {
            get {
                return ResourceManager.GetString("登录", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登录 Minecraft.
        /// </summary>
        public static string 登录Minecraft {
            get {
                return ResourceManager.GetString("登录Minecraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 视图模型实例与指定类型不匹配.
        /// </summary>
        public static string 视图模型实例与指定类型不匹配 {
            get {
                return ResourceManager.GetString("视图模型实例与指定类型不匹配", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 离线.
        /// </summary>
        public static string 离线 {
            get {
                return ResourceManager.GetString("离线", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 离线登录.
        /// </summary>
        public static string 离线登录 {
            get {
                return ResourceManager.GetString("离线登录", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 空.
        /// </summary>
        public static string 空 {
            get {
                return ResourceManager.GetString("空", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 角色名称.
        /// </summary>
        public static string 角色名称 {
            get {
                return ResourceManager.GetString("角色名称", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 许可证.
        /// </summary>
        public static string 许可证 {
            get {
                return ResourceManager.GetString("许可证", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置.
        /// </summary>
        public static string 设置 {
            get {
                return ResourceManager.GetString("设置", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 说明.
        /// </summary>
        public static string 说明 {
            get {
                return ResourceManager.GetString("说明", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 账户.
        /// </summary>
        public static string 账户 {
            get {
                return ResourceManager.GetString("账户", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 账户管理.
        /// </summary>
        public static string 账户管理 {
            get {
                return ResourceManager.GetString("账户管理", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 跳过加载器.
        /// </summary>
        public static string 跳过加载器 {
            get {
                return ResourceManager.GetString("跳过加载器", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输入.
        /// </summary>
        public static string 输入 {
            get {
                return ResourceManager.GetString("输入", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输入密码.
        /// </summary>
        public static string 输入密码 {
            get {
                return ResourceManager.GetString("输入密码", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输入电子邮件.
        /// </summary>
        public static string 输入电子邮件 {
            get {
                return ResourceManager.GetString("输入电子邮件", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输入角色名称.
        /// </summary>
        public static string 输入角色名称 {
            get {
                return ResourceManager.GetString("输入角色名称", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输入邮箱.
        /// </summary>
        public static string 输入邮箱 {
            get {
                return ResourceManager.GetString("输入邮箱", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 返回.
        /// </summary>
        public static string 返回 {
            get {
                return ResourceManager.GetString("返回", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退出.
        /// </summary>
        public static string 退出 {
            get {
                return ResourceManager.GetString("退出", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退出登录.
        /// </summary>
        public static string 退出登录 {
            get {
                return ResourceManager.GetString("退出登录", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择 Minecraft.
        /// </summary>
        public static string 选择_Minecraft {
            get {
                return ResourceManager.GetString("选择 Minecraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择 Mod 加载器.
        /// </summary>
        public static string 选择_Mod_加载器 {
            get {
                return ResourceManager.GetString("选择 Mod 加载器", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择版本.
        /// </summary>
        public static string 选择版本 {
            get {
                return ResourceManager.GetString("选择版本", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 预览.
        /// </summary>
        public static string 预览 {
            get {
                return ResourceManager.GetString("预览", resourceCulture);
            }
        }
    }
}
