using System;
using System.Linq;
using Avalonia;
using Avalonia.Controls.ApplicationLifetimes;
using Avalonia.Data.Core.Plugins;
using Avalonia.Markup.Xaml;
using MFToolkit.App;
using MFToolkit.DependencyInjection;
using MFToolkit.Minecraft.Extensions.DependencyInjection;
using MFToolkit.Minecraft.Services.Java.Interfaces;
using Microsoft.Extensions.DependencyInjection;
using OriginX.Common.Routes.Extensions;
using OriginX.Configurations;
using OriginX.DependencyInjection.AutoGenerated;
using OriginX.Utils;
using OriginX.ViewModels;
using OriginX.Views;
using SukiUI.Dialogs;
using SukiUI.Toasts;

namespace OriginX;

public partial class App : Application
{
    public override void Initialize()
    {
        AvaloniaXamlLoader.Load(this);
    }

    public override void OnFrameworkInitializationCompleted()
    {
        IServiceCollection services = new ServiceCollection();
        services.AddOptionsConfiguration();
        services.AddAutoInjectServices();
        services.AddRoutes();
        services.AddSingleton<ISukiToastManager, SukiToastManager>();
        services.AddSingleton<ISukiDialogManager, SukiDialogManager>();
        services.AddMinecraftServices(options => { options.ClientId = "你的ClientId"; });
        // 进行内部DI注入，最后注入因为内部有ServiceProvider的构建使用
        services.AddInjectServices();
        // DataTemplates.Add(new ViewLocator(views));
        if (ApplicationLifetime is IClassicDesktopStyleApplicationLifetime desktop)
        {
            // Avoid duplicate validations from both Avalonia and the CommunityToolkit. 
            // More info: https://docs.avaloniaui.net/docs/guides/development-guides/data-validation#manage-validationplugins
            DisableAvaloniaDataAnnotationValidation();
            var pageModel = MFApp.GetService<PageCurrentViewModel>();
            var mainWindow = MFApp.GetService<MainWindow>() ?? throw new Exception("未进行主容器注入");
            mainWindow.DataContext = pageModel;
            desktop.MainWindow = mainWindow;
            ClipboardUtil.SetWindow(desktop.MainWindow);
        }


        base.OnFrameworkInitializationCompleted();
    }

    private void DisableAvaloniaDataAnnotationValidation()
    {
        // Get an array of plugins to remove
        var dataValidationPluginsToRemove =
            BindingPlugins.DataValidators.OfType<DataAnnotationsValidationPlugin>().ToArray();

        // remove each entry found
        foreach (var plugin in dataValidationPluginsToRemove)
        {
            BindingPlugins.DataValidators.Remove(plugin);
        }
    }
}